build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'php-clover'